// Comprehensive list of 200+ timezones organized by region
// This file contains all available timezones for the World Clock Extension

const allTimezones = [
  // North America - United States
  { name: 'New York', timezone: 'America/New_York', flag: '🇺🇸', region: 'North America' },
  { name: 'Los Angeles', timezone: 'America/Los_Angeles', flag: '🇺🇸', region: 'North America' },
  { name: 'Chicago', timezone: 'America/Chicago', flag: '🇺🇸', region: 'North America' },
  { name: 'Denver', timezone: 'America/Denver', flag: '🇺🇸', region: 'North America' },
  { name: 'Phoenix', timezone: 'America/Phoenix', flag: '🇺🇸', region: 'North America' },
  { name: 'Anchorage', timezone: 'America/Anchorage', flag: '🇺🇸', region: 'North America' },
  { name: 'Honolulu', timezone: 'Pacific/Honolulu', flag: '🇺🇸', region: 'North America' },
  { name: 'Detroit', timezone: 'America/Detroit', flag: '🇺🇸', region: 'North America' },
  { name: 'Miami', timezone: 'America/New_York', flag: '🇺🇸', region: 'North America' },
  { name: 'Seattle', timezone: 'America/Los_Angeles', flag: '🇺🇸', region: 'North America' },
  { name: 'Boston', timezone: 'America/New_York', flag: '🇺🇸', region: 'North America' },
  { name: 'Atlanta', timezone: 'America/New_York', flag: '🇺🇸', region: 'North America' },
  { name: 'Dallas', timezone: 'America/Chicago', flag: '🇺🇸', region: 'North America' },
  { name: 'Houston', timezone: 'America/Chicago', flag: '🇺🇸', region: 'North America' },
  { name: 'Las Vegas', timezone: 'America/Los_Angeles', flag: '🇺🇸', region: 'North America' },
  { name: 'Portland', timezone: 'America/Los_Angeles', flag: '🇺🇸', region: 'North America' },
  { name: 'San Francisco', timezone: 'America/Los_Angeles', flag: '🇺🇸', region: 'North America' },
  { name: 'San Diego', timezone: 'America/Los_Angeles', flag: '🇺🇸', region: 'North America' },
  { name: 'Minneapolis', timezone: 'America/Chicago', flag: '🇺🇸', region: 'North America' },
  { name: 'Kansas City', timezone: 'America/Chicago', flag: '🇺🇸', region: 'North America' },
  { name: 'New Orleans', timezone: 'America/Chicago', flag: '🇺🇸', region: 'North America' },
  { name: 'Nashville', timezone: 'America/Chicago', flag: '🇺🇸', region: 'North America' },
  { name: 'Indianapolis', timezone: 'America/Indiana/Indianapolis', flag: '🇺🇸', region: 'North America' },
  { name: 'Philadelphia', timezone: 'America/New_York', flag: '🇺🇸', region: 'North America' },
  { name: 'Washington DC', timezone: 'America/New_York', flag: '🇺🇸', region: 'North America' },
  { name: 'Baltimore', timezone: 'America/New_York', flag: '🇺🇸', region: 'North America' },
  { name: 'Charlotte', timezone: 'America/New_York', flag: '🇺🇸', region: 'North America' },
  { name: 'Jacksonville', timezone: 'America/New_York', flag: '🇺🇸', region: 'North America' },
  { name: 'Tampa', timezone: 'America/New_York', flag: '🇺🇸', region: 'North America' },
  { name: 'Orlando', timezone: 'America/New_York', flag: '🇺🇸', region: 'North America' },
  { name: 'Memphis', timezone: 'America/Chicago', flag: '🇺🇸', region: 'North America' },
  { name: 'Milwaukee', timezone: 'America/Chicago', flag: '🇺🇸', region: 'North America' },
  { name: 'Cleveland', timezone: 'America/New_York', flag: '🇺🇸', region: 'North America' },
  { name: 'Columbus', timezone: 'America/New_York', flag: '🇺🇸', region: 'North America' },
  { name: 'Cincinnati', timezone: 'America/New_York', flag: '🇺🇸', region: 'North America' },
  { name: 'Pittsburgh', timezone: 'America/New_York', flag: '🇺🇸', region: 'North America' },
  { name: 'Buffalo', timezone: 'America/New_York', flag: '🇺🇸', region: 'North America' },
  { name: 'Rochester', timezone: 'America/New_York', flag: '🇺🇸', region: 'North America' },
  { name: 'Albany', timezone: 'America/New_York', flag: '🇺🇸', region: 'North America' },
  { name: 'Hartford', timezone: 'America/New_York', flag: '🇺🇸', region: 'North America' },
  { name: 'Providence', timezone: 'America/New_York', flag: '🇺🇸', region: 'North America' },
  { name: 'Richmond', timezone: 'America/New_York', flag: '🇺🇸', region: 'North America' },
  { name: 'Raleigh', timezone: 'America/New_York', flag: '🇺🇸', region: 'North America' },
  { name: 'Louisville', timezone: 'America/New_York', flag: '🇺🇸', region: 'North America' },
  { name: 'Lexington', timezone: 'America/New_York', flag: '🇺🇸', region: 'North America' },
  { name: 'Birmingham', timezone: 'America/Chicago', flag: '🇺🇸', region: 'North America' },
  { name: 'Montgomery', timezone: 'America/Chicago', flag: '🇺🇸', region: 'North America' },
  { name: 'Mobile', timezone: 'America/Chicago', flag: '🇺🇸', region: 'North America' },
  { name: 'Little Rock', timezone: 'America/Chicago', flag: '🇺🇸', region: 'North America' },
  { name: 'Oklahoma City', timezone: 'America/Chicago', flag: '🇺🇸', region: 'North America' },
  { name: 'Tulsa', timezone: 'America/Chicago', flag: '🇺🇸', region: 'North America' },
  { name: 'Wichita', timezone: 'America/Chicago', flag: '🇺🇸', region: 'North America' },
  { name: 'Omaha', timezone: 'America/Chicago', flag: '🇺🇸', region: 'North America' },
  { name: 'Des Moines', timezone: 'America/Chicago', flag: '🇺🇸', region: 'North America' },
  { name: 'Fargo', timezone: 'America/Chicago', flag: '🇺🇸', region: 'North America' },
  { name: 'Sioux Falls', timezone: 'America/Chicago', flag: '🇺🇸', region: 'North America' },
  { name: 'Bismarck', timezone: 'America/Chicago', flag: '🇺🇸', region: 'North America' },
  { name: 'Billings', timezone: 'America/Denver', flag: '🇺🇸', region: 'North America' },
  { name: 'Cheyenne', timezone: 'America/Denver', flag: '🇺🇸', region: 'North America' },
  { name: 'Salt Lake City', timezone: 'America/Denver', flag: '🇺🇸', region: 'North America' },
  { name: 'Boise', timezone: 'America/Boise', flag: '🇺🇸', region: 'North America' },
  { name: 'Albuquerque', timezone: 'America/Denver', flag: '🇺🇸', region: 'North America' },
  { name: 'Tucson', timezone: 'America/Phoenix', flag: '🇺🇸', region: 'North America' },
  { name: 'El Paso', timezone: 'America/Denver', flag: '🇺🇸', region: 'North America' },
  { name: 'Juneau', timezone: 'America/Juneau', flag: '🇺🇸', region: 'North America' },
  { name: 'Fairbanks', timezone: 'America/Anchorage', flag: '🇺🇸', region: 'North America' },
  
  // North America - Canada
  { name: 'Toronto', timezone: 'America/Toronto', flag: '🇨🇦', region: 'North America' },
  { name: 'Vancouver', timezone: 'America/Vancouver', flag: '🇨🇦', region: 'North America' },
  { name: 'Montreal', timezone: 'America/Toronto', flag: '🇨🇦', region: 'North America' },
  { name: 'Calgary', timezone: 'America/Edmonton', flag: '🇨🇦', region: 'North America' },
  { name: 'Edmonton', timezone: 'America/Edmonton', flag: '🇨🇦', region: 'North America' },
  { name: 'Ottawa', timezone: 'America/Toronto', flag: '🇨🇦', region: 'North America' },
  { name: 'Winnipeg', timezone: 'America/Winnipeg', flag: '🇨🇦', region: 'North America' },
  { name: 'Quebec City', timezone: 'America/Toronto', flag: '🇨🇦', region: 'North America' },
  { name: 'Halifax', timezone: 'America/Halifax', flag: '🇨🇦', region: 'North America' },
  { name: 'St. John\'s', timezone: 'America/St_Johns', flag: '🇨🇦', region: 'North America' },
  { name: 'Victoria', timezone: 'America/Vancouver', flag: '🇨🇦', region: 'North America' },
  { name: 'Regina', timezone: 'America/Regina', flag: '🇨🇦', region: 'North America' },
  { name: 'Saskatoon', timezone: 'America/Regina', flag: '🇨🇦', region: 'North America' },
  { name: 'Thunder Bay', timezone: 'America/Toronto', flag: '🇨🇦', region: 'North America' },
  { name: 'Whitehorse', timezone: 'America/Whitehorse', flag: '🇨🇦', region: 'North America' },
  { name: 'Yellowknife', timezone: 'America/Yellowknife', flag: '🇨🇦', region: 'North America' },
  { name: 'Iqaluit', timezone: 'America/Iqaluit', flag: '🇨🇦', region: 'North America' },
  
  // North America - Mexico & Central America
  { name: 'Mexico City', timezone: 'America/Mexico_City', flag: '🇲🇽', region: 'North America' },
  { name: 'Guadalajara', timezone: 'America/Mexico_City', flag: '🇲🇽', region: 'North America' },
  { name: 'Monterrey', timezone: 'America/Monterrey', flag: '🇲🇽', region: 'North America' },
  { name: 'Tijuana', timezone: 'America/Tijuana', flag: '🇲🇽', region: 'North America' },
  { name: 'Cancun', timezone: 'America/Cancun', flag: '🇲🇽', region: 'North America' },
  { name: 'Merida', timezone: 'America/Merida', flag: '🇲🇽', region: 'North America' },
  { name: 'Mazatlan', timezone: 'America/Mazatlan', flag: '🇲🇽', region: 'North America' },
  { name: 'Chihuahua', timezone: 'America/Chihuahua', flag: '🇲🇽', region: 'North America' },
  { name: 'Hermosillo', timezone: 'America/Hermosillo', flag: '🇲🇽', region: 'North America' },
  { name: 'Guatemala City', timezone: 'America/Guatemala', flag: '🇬🇹', region: 'Central America' },
  { name: 'San Salvador', timezone: 'America/El_Salvador', flag: '🇸🇻', region: 'Central America' },
  { name: 'Tegucigalpa', timezone: 'America/Tegucigalpa', flag: '🇭🇳', region: 'Central America' },
  { name: 'Managua', timezone: 'America/Managua', flag: '🇳🇮', region: 'Central America' },
  { name: 'San Jose', timezone: 'America/Costa_Rica', flag: '🇨🇷', region: 'Central America' },
  { name: 'Panama City', timezone: 'America/Panama', flag: '🇵🇦', region: 'Central America' },
  { name: 'Belize City', timezone: 'America/Belize', flag: '🇧🇿', region: 'Central America' },
  
  // South America
  { name: 'São Paulo', timezone: 'America/Sao_Paulo', flag: '🇧🇷', region: 'South America' },
  { name: 'Rio de Janeiro', timezone: 'America/Sao_Paulo', flag: '🇧🇷', region: 'South America' },
  { name: 'Brasilia', timezone: 'America/Sao_Paulo', flag: '🇧🇷', region: 'South America' },
  { name: 'Buenos Aires', timezone: 'America/Buenos_Aires', flag: '🇦🇷', region: 'South America' },
  { name: 'Santiago', timezone: 'America/Santiago', flag: '🇨🇱', region: 'South America' },
  { name: 'Lima', timezone: 'America/Lima', flag: '🇵🇪', region: 'South America' },
  { name: 'Bogota', timezone: 'America/Bogota', flag: '🇨🇴', region: 'South America' },
  { name: 'Caracas', timezone: 'America/Caracas', flag: '🇻🇪', region: 'South America' },
  { name: 'Quito', timezone: 'America/Guayaquil', flag: '🇪🇨', region: 'South America' },
  { name: 'La Paz', timezone: 'America/La_Paz', flag: '🇧🇴', region: 'South America' },
  { name: 'Asuncion', timezone: 'America/Asuncion', flag: '🇵🇾', region: 'South America' },
  { name: 'Montevideo', timezone: 'America/Montevideo', flag: '🇺🇾', region: 'South America' },
  { name: 'Georgetown', timezone: 'America/Guyana', flag: '🇬🇾', region: 'South America' },
  { name: 'Paramaribo', timezone: 'America/Paramaribo', flag: '🇸🇷', region: 'South America' },
  { name: 'Cayenne', timezone: 'America/Cayenne', flag: '🇬🇫', region: 'South America' },
  { name: 'Fortaleza', timezone: 'America/Fortaleza', flag: '🇧🇷', region: 'South America' },
  { name: 'Recife', timezone: 'America/Recife', flag: '🇧🇷', region: 'South America' },
  { name: 'Salvador', timezone: 'America/Bahia', flag: '🇧🇷', region: 'South America' },
  { name: 'Manaus', timezone: 'America/Manaus', flag: '🇧🇷', region: 'South America' },
  { name: 'Belem', timezone: 'America/Belem', flag: '🇧🇷', region: 'South America' },
  { name: 'Cuiaba', timezone: 'America/Cuiaba', flag: '🇧🇷', region: 'South America' },
  { name: 'Campo Grande', timezone: 'America/Campo_Grande', flag: '🇧🇷', region: 'South America' },
  { name: 'Porto Alegre', timezone: 'America/Sao_Paulo', flag: '🇧🇷', region: 'South America' },
  { name: 'Curitiba', timezone: 'America/Sao_Paulo', flag: '🇧🇷', region: 'South America' },
  { name: 'Florianopolis', timezone: 'America/Sao_Paulo', flag: '🇧🇷', region: 'South America' },
  { name: 'Medellin', timezone: 'America/Bogota', flag: '🇨🇴', region: 'South America' },
  { name: 'Cali', timezone: 'America/Bogota', flag: '🇨🇴', region: 'South America' },
  { name: 'Barranquilla', timezone: 'America/Bogota', flag: '🇨🇴', region: 'South America' },
  { name: 'Guayaquil', timezone: 'America/Guayaquil', flag: '🇪🇨', region: 'South America' },
  { name: 'Maracaibo', timezone: 'America/Caracas', flag: '🇻🇪', region: 'South America' },
  { name: 'Valencia', timezone: 'America/Caracas', flag: '🇻🇪', region: 'South America' },
  { name: 'Cordoba', timezone: 'America/Argentina/Cordoba', flag: '🇦🇷', region: 'South America' },
  { name: 'Rosario', timezone: 'America/Argentina/Buenos_Aires', flag: '🇦🇷', region: 'South America' },
  { name: 'Mendoza', timezone: 'America/Argentina/Mendoza', flag: '🇦🇷', region: 'South America' },
  { name: 'Valparaiso', timezone: 'America/Santiago', flag: '🇨🇱', region: 'South America' },
  { name: 'Arequipa', timezone: 'America/Lima', flag: '🇵🇪', region: 'South America' },
  { name: 'Cusco', timezone: 'America/Lima', flag: '🇵🇪', region: 'South America' },
  
  // Europe - Western
  { name: 'London', timezone: 'Europe/London', flag: '🇬🇧', region: 'Europe' },
  { name: 'Paris', timezone: 'Europe/Paris', flag: '🇫🇷', region: 'Europe' },
  { name: 'Berlin', timezone: 'Europe/Berlin', flag: '🇩🇪', region: 'Europe' },
  { name: 'Madrid', timezone: 'Europe/Madrid', flag: '🇪🇸', region: 'Europe' },
  { name: 'Rome', timezone: 'Europe/Rome', flag: '🇮🇹', region: 'Europe' },
  { name: 'Amsterdam', timezone: 'Europe/Amsterdam', flag: '🇳🇱', region: 'Europe' },
  { name: 'Brussels', timezone: 'Europe/Brussels', flag: '🇧🇪', region: 'Europe' },
  { name: 'Vienna', timezone: 'Europe/Vienna', flag: '🇦🇹', region: 'Europe' },
  { name: 'Zurich', timezone: 'Europe/Zurich', flag: '🇨🇭', region: 'Europe' },
  { name: 'Stockholm', timezone: 'Europe/Stockholm', flag: '🇸🇪', region: 'Europe' },
  { name: 'Oslo', timezone: 'Europe/Oslo', flag: '🇳🇴', region: 'Europe' },
  { name: 'Copenhagen', timezone: 'Europe/Copenhagen', flag: '🇩🇰', region: 'Europe' },
  { name: 'Helsinki', timezone: 'Europe/Helsinki', flag: '🇫🇮', region: 'Europe' },
  { name: 'Dublin', timezone: 'Europe/Dublin', flag: '🇮🇪', region: 'Europe' },
  { name: 'Lisbon', timezone: 'Europe/Lisbon', flag: '🇵🇹', region: 'Europe' },
  { name: 'Luxembourg', timezone: 'Europe/Luxembourg', flag: '🇱🇺', region: 'Europe' },
  { name: 'Monaco', timezone: 'Europe/Monaco', flag: '🇲🇨', region: 'Europe' },
  { name: 'Andorra', timezone: 'Europe/Andorra', flag: '🇦🇩', region: 'Europe' },
  { name: 'Barcelona', timezone: 'Europe/Madrid', flag: '🇪🇸', region: 'Europe' },
  { name: 'Valencia', timezone: 'Europe/Madrid', flag: '🇪🇸', region: 'Europe' },
  { name: 'Seville', timezone: 'Europe/Madrid', flag: '🇪🇸', region: 'Europe' },
  { name: 'Milan', timezone: 'Europe/Rome', flag: '🇮🇹', region: 'Europe' },
  { name: 'Naples', timezone: 'Europe/Rome', flag: '🇮🇹', region: 'Europe' },
  { name: 'Turin', timezone: 'Europe/Rome', flag: '🇮🇹', region: 'Europe' },
  { name: 'Venice', timezone: 'Europe/Rome', flag: '🇮🇹', region: 'Europe' },
  { name: 'Florence', timezone: 'Europe/Rome', flag: '🇮🇹', region: 'Europe' },
  { name: 'Munich', timezone: 'Europe/Berlin', flag: '🇩🇪', region: 'Europe' },
  { name: 'Hamburg', timezone: 'Europe/Berlin', flag: '🇩🇪', region: 'Europe' },
  { name: 'Frankfurt', timezone: 'Europe/Berlin', flag: '🇩🇪', region: 'Europe' },
  { name: 'Cologne', timezone: 'Europe/Berlin', flag: '🇩🇪', region: 'Europe' },
  { name: 'Stuttgart', timezone: 'Europe/Berlin', flag: '🇩🇪', region: 'Europe' },
  { name: 'Düsseldorf', timezone: 'Europe/Berlin', flag: '🇩🇪', region: 'Europe' },
  { name: 'Rotterdam', timezone: 'Europe/Amsterdam', flag: '🇳🇱', region: 'Europe' },
  { name: 'The Hague', timezone: 'Europe/Amsterdam', flag: '🇳🇱', region: 'Europe' },
  { name: 'Utrecht', timezone: 'Europe/Amsterdam', flag: '🇳🇱', region: 'Europe' },
  { name: 'Antwerp', timezone: 'Europe/Brussels', flag: '🇧🇪', region: 'Europe' },
  { name: 'Ghent', timezone: 'Europe/Brussels', flag: '🇧🇪', region: 'Europe' },
  { name: 'Geneva', timezone: 'Europe/Zurich', flag: '🇨🇭', region: 'Europe' },
  { name: 'Basel', timezone: 'Europe/Zurich', flag: '🇨🇭', region: 'Europe' },
  { name: 'Bern', timezone: 'Europe/Zurich', flag: '🇨🇭', region: 'Europe' },
  { name: 'Gothenburg', timezone: 'Europe/Stockholm', flag: '🇸🇪', region: 'Europe' },
  { name: 'Malmo', timezone: 'Europe/Stockholm', flag: '🇸🇪', region: 'Europe' },
  { name: 'Bergen', timezone: 'Europe/Oslo', flag: '🇳🇴', region: 'Europe' },
  { name: 'Trondheim', timezone: 'Europe/Oslo', flag: '🇳🇴', region: 'Europe' },
  { name: 'Aarhus', timezone: 'Europe/Copenhagen', flag: '🇩🇰', region: 'Europe' },
  { name: 'Odense', timezone: 'Europe/Copenhagen', flag: '🇩🇰', region: 'Europe' },
  { name: 'Tampere', timezone: 'Europe/Helsinki', flag: '🇫🇮', region: 'Europe' },
  { name: 'Turku', timezone: 'Europe/Helsinki', flag: '🇫🇮', region: 'Europe' },
  { name: 'Cork', timezone: 'Europe/Dublin', flag: '🇮🇪', region: 'Europe' },
  { name: 'Porto', timezone: 'Europe/Lisbon', flag: '🇵🇹', region: 'Europe' },
  { name: 'Coimbra', timezone: 'Europe/Lisbon', flag: '🇵🇹', region: 'Europe' },
  
  // Europe - Eastern
  { name: 'Moscow', timezone: 'Europe/Moscow', flag: '🇷🇺', region: 'Europe' },
  { name: 'Warsaw', timezone: 'Europe/Warsaw', flag: '🇵🇱', region: 'Europe' },
  { name: 'Prague', timezone: 'Europe/Prague', flag: '🇨🇿', region: 'Europe' },
  { name: 'Budapest', timezone: 'Europe/Budapest', flag: '🇭🇺', region: 'Europe' },
  { name: 'Bucharest', timezone: 'Europe/Bucharest', flag: '🇷🇴', region: 'Europe' },
  { name: 'Sofia', timezone: 'Europe/Sofia', flag: '🇧🇬', region: 'Europe' },
  { name: 'Athens', timezone: 'Europe/Athens', flag: '🇬🇷', region: 'Europe' },
  { name: 'Belgrade', timezone: 'Europe/Belgrade', flag: '🇷🇸', region: 'Europe' },
  { name: 'Zagreb', timezone: 'Europe/Zagreb', flag: '🇭🇷', region: 'Europe' },
  { name: 'Ljubljana', timezone: 'Europe/Ljubljana', flag: '🇸🇮', region: 'Europe' },
  { name: 'Bratislava', timezone: 'Europe/Bratislava', flag: '🇸🇰', region: 'Europe' },
  { name: 'Kiev', timezone: 'Europe/Kiev', flag: '🇺🇦', region: 'Europe' },
  { name: 'Minsk', timezone: 'Europe/Minsk', flag: '🇧🇾', region: 'Europe' },
  { name: 'Vilnius', timezone: 'Europe/Vilnius', flag: '🇱🇹', region: 'Europe' },
  { name: 'Riga', timezone: 'Europe/Riga', flag: '🇱🇻', region: 'Europe' },
  { name: 'Tallinn', timezone: 'Europe/Tallinn', flag: '🇪🇪', region: 'Europe' },
  { name: 'Helsinki', timezone: 'Europe/Helsinki', flag: '🇫🇮', region: 'Europe' },
  { name: 'Krakow', timezone: 'Europe/Warsaw', flag: '🇵🇱', region: 'Europe' },
  { name: 'Gdansk', timezone: 'Europe/Warsaw', flag: '🇵🇱', region: 'Europe' },
  { name: 'Wroclaw', timezone: 'Europe/Warsaw', flag: '🇵🇱', region: 'Europe' },
  { name: 'Brno', timezone: 'Europe/Prague', flag: '🇨🇿', region: 'Europe' },
  { name: 'Ostrava', timezone: 'Europe/Prague', flag: '🇨🇿', region: 'Europe' },
  { name: 'Debrecen', timezone: 'Europe/Budapest', flag: '🇭🇺', region: 'Europe' },
  { name: 'Szeged', timezone: 'Europe/Budapest', flag: '🇭🇺', region: 'Europe' },
  { name: 'Cluj-Napoca', timezone: 'Europe/Bucharest', flag: '🇷🇴', region: 'Europe' },
  { name: 'Timisoara', timezone: 'Europe/Bucharest', flag: '🇷🇴', region: 'Europe' },
  { name: 'Plovdiv', timezone: 'Europe/Sofia', flag: '🇧🇬', region: 'Europe' },
  { name: 'Varna', timezone: 'Europe/Sofia', flag: '🇧🇬', region: 'Europe' },
  { name: 'Thessaloniki', timezone: 'Europe/Athens', flag: '🇬🇷', region: 'Europe' },
  { name: 'Patras', timezone: 'Europe/Athens', flag: '🇬🇷', region: 'Europe' },
  { name: 'Novi Sad', timezone: 'Europe/Belgrade', flag: '🇷🇸', region: 'Europe' },
  { name: 'Nis', timezone: 'Europe/Belgrade', flag: '🇷🇸', region: 'Europe' },
  { name: 'Split', timezone: 'Europe/Zagreb', flag: '🇭🇷', region: 'Europe' },
  { name: 'Dubrovnik', timezone: 'Europe/Zagreb', flag: '🇭🇷', region: 'Europe' },
  { name: 'Odessa', timezone: 'Europe/Kiev', flag: '🇺🇦', region: 'Europe' },
  { name: 'Kharkiv', timezone: 'Europe/Kiev', flag: '🇺🇦', region: 'Europe' },
  { name: 'Lviv', timezone: 'Europe/Kiev', flag: '🇺🇦', region: 'Europe' },
  { name: 'St. Petersburg', timezone: 'Europe/Moscow', flag: '🇷🇺', region: 'Europe' },
  { name: 'Novosibirsk', timezone: 'Asia/Novosibirsk', flag: '🇷🇺', region: 'Asia' },
  { name: 'Yekaterinburg', timezone: 'Asia/Yekaterinburg', flag: '🇷🇺', region: 'Asia' },
  { name: 'Kazan', timezone: 'Europe/Moscow', flag: '🇷🇺', region: 'Europe' },
  { name: 'Nizhny Novgorod', timezone: 'Europe/Moscow', flag: '🇷🇺', region: 'Europe' },
  { name: 'Samara', timezone: 'Europe/Samara', flag: '🇷🇺', region: 'Europe' },
  { name: 'Rostov-on-Don', timezone: 'Europe/Moscow', flag: '🇷🇺', region: 'Europe' },
  { name: 'Volgograd', timezone: 'Europe/Volgograd', flag: '🇷🇺', region: 'Europe' },
  
  // Asia - Middle East
  { name: 'Dubai', timezone: 'Asia/Dubai', flag: '🇦🇪', region: 'Middle East' },
  { name: 'Abu Dhabi', timezone: 'Asia/Dubai', flag: '🇦🇪', region: 'Middle East' },
  { name: 'Riyadh', timezone: 'Asia/Riyadh', flag: '🇸🇦', region: 'Middle East' },
  { name: 'Jeddah', timezone: 'Asia/Riyadh', flag: '🇸🇦', region: 'Middle East' },
  { name: 'Mecca', timezone: 'Asia/Riyadh', flag: '🇸🇦', region: 'Middle East' },
  { name: 'Medina', timezone: 'Asia/Riyadh', flag: '🇸🇦', region: 'Middle East' },
  { name: 'Dammam', timezone: 'Asia/Riyadh', flag: '🇸🇦', region: 'Middle East' },
  { name: 'Kuwait City', timezone: 'Asia/Kuwait', flag: '🇰🇼', region: 'Middle East' },
  { name: 'Manama', timezone: 'Asia/Bahrain', flag: '🇧🇭', region: 'Middle East' },
  { name: 'Doha', timezone: 'Asia/Qatar', flag: '🇶🇦', region: 'Middle East' },
  { name: 'Muscat', timezone: 'Asia/Muscat', flag: '🇴🇲', region: 'Middle East' },
  { name: 'Sana\'a', timezone: 'Asia/Aden', flag: '🇾🇪', region: 'Middle East' },
  { name: 'Baghdad', timezone: 'Asia/Baghdad', flag: '🇮🇶', region: 'Middle East' },
  { name: 'Basra', timezone: 'Asia/Baghdad', flag: '🇮🇶', region: 'Middle East' },
  { name: 'Tehran', timezone: 'Asia/Tehran', flag: '🇮🇷', region: 'Middle East' },
  { name: 'Isfahan', timezone: 'Asia/Tehran', flag: '🇮🇷', region: 'Middle East' },
  { name: 'Shiraz', timezone: 'Asia/Tehran', flag: '🇮🇷', region: 'Middle East' },
  { name: 'Tabriz', timezone: 'Asia/Tehran', flag: '🇮🇷', region: 'Middle East' },
  { name: 'Tel Aviv', timezone: 'Asia/Jerusalem', flag: '🇮🇱', region: 'Middle East' },
  { name: 'Jerusalem', timezone: 'Asia/Jerusalem', flag: '🇮🇱', region: 'Middle East' },
  { name: 'Haifa', timezone: 'Asia/Jerusalem', flag: '🇮🇱', region: 'Middle East' },
  { name: 'Beirut', timezone: 'Asia/Beirut', flag: '🇱🇧', region: 'Middle East' },
  { name: 'Damascus', timezone: 'Asia/Damascus', flag: '🇸🇾', region: 'Middle East' },
  { name: 'Amman', timezone: 'Asia/Amman', flag: '🇯🇴', region: 'Middle East' },
  { name: 'Nicosia', timezone: 'Asia/Nicosia', flag: '🇨🇾', region: 'Middle East' },
  { name: 'Istanbul', timezone: 'Europe/Istanbul', flag: '🇹🇷', region: 'Middle East' },
  { name: 'Ankara', timezone: 'Europe/Istanbul', flag: '🇹🇷', region: 'Middle East' },
  { name: 'Izmir', timezone: 'Europe/Istanbul', flag: '🇹🇷', region: 'Middle East' },
  { name: 'Antalya', timezone: 'Europe/Istanbul', flag: '🇹🇷', region: 'Middle East' },
  { name: 'Bursa', timezone: 'Europe/Istanbul', flag: '🇹🇷', region: 'Middle East' },
  { name: 'Cairo', timezone: 'Africa/Cairo', flag: '🇪🇬', region: 'Middle East' },
  { name: 'Alexandria', timezone: 'Africa/Cairo', flag: '🇪🇬', region: 'Middle East' },
  { name: 'Giza', timezone: 'Africa/Cairo', flag: '🇪🇬', region: 'Middle East' },
  
  // Asia - South Asia
  { name: 'Mumbai', timezone: 'Asia/Kolkata', flag: '🇮🇳', region: 'South Asia' },
  { name: 'Delhi', timezone: 'Asia/Kolkata', flag: '🇮🇳', region: 'South Asia' },
  { name: 'Bangalore', timezone: 'Asia/Kolkata', flag: '🇮🇳', region: 'South Asia' },
  { name: 'Hyderabad', timezone: 'Asia/Kolkata', flag: '🇮🇳', region: 'South Asia' },
  { name: 'Chennai', timezone: 'Asia/Kolkata', flag: '🇮🇳', region: 'South Asia' },
  { name: 'Kolkata', timezone: 'Asia/Kolkata', flag: '🇮🇳', region: 'South Asia' },
  { name: 'Pune', timezone: 'Asia/Kolkata', flag: '🇮🇳', region: 'South Asia' },
  { name: 'Ahmedabad', timezone: 'Asia/Kolkata', flag: '🇮🇳', region: 'South Asia' },
  { name: 'Surat', timezone: 'Asia/Kolkata', flag: '🇮🇳', region: 'South Asia' },
  { name: 'Jaipur', timezone: 'Asia/Kolkata', flag: '🇮🇳', region: 'South Asia' },
  { name: 'Lucknow', timezone: 'Asia/Kolkata', flag: '🇮🇳', region: 'South Asia' },
  { name: 'Kanpur', timezone: 'Asia/Kolkata', flag: '🇮🇳', region: 'South Asia' },
  { name: 'Nagpur', timezone: 'Asia/Kolkata', flag: '🇮🇳', region: 'South Asia' },
  { name: 'Indore', timezone: 'Asia/Kolkata', flag: '🇮🇳', region: 'South Asia' },
  { name: 'Thane', timezone: 'Asia/Kolkata', flag: '🇮🇳', region: 'South Asia' },
  { name: 'Bhopal', timezone: 'Asia/Kolkata', flag: '🇮🇳', region: 'South Asia' },
  { name: 'Visakhapatnam', timezone: 'Asia/Kolkata', flag: '🇮🇳', region: 'South Asia' },
  { name: 'Patna', timezone: 'Asia/Kolkata', flag: '🇮🇳', region: 'South Asia' },
  { name: 'Vadodara', timezone: 'Asia/Kolkata', flag: '🇮🇳', region: 'South Asia' },
  { name: 'Ghaziabad', timezone: 'Asia/Kolkata', flag: '🇮🇳', region: 'South Asia' },
  { name: 'Ludhiana', timezone: 'Asia/Kolkata', flag: '🇮🇳', region: 'South Asia' },
  { name: 'Agra', timezone: 'Asia/Kolkata', flag: '🇮🇳', region: 'South Asia' },
  { name: 'Nashik', timezone: 'Asia/Kolkata', flag: '🇮🇳', region: 'South Asia' },
  { name: 'Faridabad', timezone: 'Asia/Kolkata', flag: '🇮🇳', region: 'South Asia' },
  { name: 'Meerut', timezone: 'Asia/Kolkata', flag: '🇮🇳', region: 'South Asia' },
  { name: 'Rajkot', timezone: 'Asia/Kolkata', flag: '🇮🇳', region: 'South Asia' },
  { name: 'Varanasi', timezone: 'Asia/Kolkata', flag: '🇮🇳', region: 'South Asia' },
  { name: 'Srinagar', timezone: 'Asia/Kolkata', flag: '🇮🇳', region: 'South Asia' },
  { name: 'Amritsar', timezone: 'Asia/Kolkata', flag: '🇮🇳', region: 'South Asia' },
  { name: 'Chandigarh', timezone: 'Asia/Kolkata', flag: '🇮🇳', region: 'South Asia' },
  { name: 'Guwahati', timezone: 'Asia/Kolkata', flag: '🇮🇳', region: 'South Asia' },
  { name: 'Imphal', timezone: 'Asia/Kolkata', flag: '🇮🇳', region: 'South Asia' },
  { name: 'Shillong', timezone: 'Asia/Kolkata', flag: '🇮🇳', region: 'South Asia' },
  { name: 'Aizawl', timezone: 'Asia/Kolkata', flag: '🇮🇳', region: 'South Asia' },
  { name: 'Kohima', timezone: 'Asia/Kolkata', flag: '🇮🇳', region: 'South Asia' },
  { name: 'Gangtok', timezone: 'Asia/Kolkata', flag: '🇮🇳', region: 'South Asia' },
  { name: 'Itanagar', timezone: 'Asia/Kolkata', flag: '🇮🇳', region: 'South Asia' },
  { name: 'Port Blair', timezone: 'Asia/Kolkata', flag: '🇮🇳', region: 'South Asia' },
  { name: 'Karachi', timezone: 'Asia/Karachi', flag: '🇵🇰', region: 'South Asia' },
  { name: 'Lahore', timezone: 'Asia/Karachi', flag: '🇵🇰', region: 'South Asia' },
  { name: 'Islamabad', timezone: 'Asia/Karachi', flag: '🇵🇰', region: 'South Asia' },
  { name: 'Faisalabad', timezone: 'Asia/Karachi', flag: '🇵🇰', region: 'South Asia' },
  { name: 'Rawalpindi', timezone: 'Asia/Karachi', flag: '🇵🇰', region: 'South Asia' },
  { name: 'Multan', timezone: 'Asia/Karachi', flag: '🇵🇰', region: 'South Asia' },
  { name: 'Peshawar', timezone: 'Asia/Karachi', flag: '🇵🇰', region: 'South Asia' },
  { name: 'Quetta', timezone: 'Asia/Karachi', flag: '🇵🇰', region: 'South Asia' },
  { name: 'Dhaka', timezone: 'Asia/Dhaka', flag: '🇧🇩', region: 'South Asia' },
  { name: 'Chittagong', timezone: 'Asia/Dhaka', flag: '🇧🇩', region: 'South Asia' },
  { name: 'Khulna', timezone: 'Asia/Dhaka', flag: '🇧🇩', region: 'South Asia' },
  { name: 'Rajshahi', timezone: 'Asia/Dhaka', flag: '🇧🇩', region: 'South Asia' },
  { name: 'Kathmandu', timezone: 'Asia/Kathmandu', flag: '🇳🇵', region: 'South Asia' },
  { name: 'Colombo', timezone: 'Asia/Colombo', flag: '🇱🇰', region: 'South Asia' },
  { name: 'Kandy', timezone: 'Asia/Colombo', flag: '🇱🇰', region: 'South Asia' },
  { name: 'Kabul', timezone: 'Asia/Kabul', flag: '🇦🇫', region: 'South Asia' },
  { name: 'Male', timezone: 'Indian/Maldives', flag: '🇲🇻', region: 'South Asia' },
  { name: 'Thimphu', timezone: 'Asia/Thimphu', flag: '🇧🇹', region: 'South Asia' },
  
  // Asia - East Asia
  { name: 'Tokyo', timezone: 'Asia/Tokyo', flag: '🇯🇵', region: 'East Asia' },
  { name: 'Osaka', timezone: 'Asia/Tokyo', flag: '🇯🇵', region: 'East Asia' },
  { name: 'Yokohama', timezone: 'Asia/Tokyo', flag: '🇯🇵', region: 'East Asia' },
  { name: 'Nagoya', timezone: 'Asia/Tokyo', flag: '🇯🇵', region: 'East Asia' },
  { name: 'Sapporo', timezone: 'Asia/Tokyo', flag: '🇯🇵', region: 'East Asia' },
  { name: 'Fukuoka', timezone: 'Asia/Tokyo', flag: '🇯🇵', region: 'East Asia' },
  { name: 'Kobe', timezone: 'Asia/Tokyo', flag: '🇯🇵', region: 'East Asia' },
  { name: 'Kyoto', timezone: 'Asia/Tokyo', flag: '🇯🇵', region: 'East Asia' },
  { name: 'Sendai', timezone: 'Asia/Tokyo', flag: '🇯🇵', region: 'East Asia' },
  { name: 'Hiroshima', timezone: 'Asia/Tokyo', flag: '🇯🇵', region: 'East Asia' },
  { name: 'Beijing', timezone: 'Asia/Shanghai', flag: '🇨🇳', region: 'East Asia' },
  { name: 'Shanghai', timezone: 'Asia/Shanghai', flag: '🇨🇳', region: 'East Asia' },
  { name: 'Guangzhou', timezone: 'Asia/Shanghai', flag: '🇨🇳', region: 'East Asia' },
  { name: 'Shenzhen', timezone: 'Asia/Shanghai', flag: '🇨🇳', region: 'East Asia' },
  { name: 'Chengdu', timezone: 'Asia/Shanghai', flag: '🇨🇳', region: 'East Asia' },
  { name: 'Chongqing', timezone: 'Asia/Shanghai', flag: '🇨🇳', region: 'East Asia' },
  { name: 'Wuhan', timezone: 'Asia/Shanghai', flag: '🇨🇳', region: 'East Asia' },
  { name: 'Xi\'an', timezone: 'Asia/Shanghai', flag: '🇨🇳', region: 'East Asia' },
  { name: 'Nanjing', timezone: 'Asia/Shanghai', flag: '🇨🇳', region: 'East Asia' },
  { name: 'Hangzhou', timezone: 'Asia/Shanghai', flag: '🇨🇳', region: 'East Asia' },
  { name: 'Tianjin', timezone: 'Asia/Shanghai', flag: '🇨🇳', region: 'East Asia' },
  { name: 'Suzhou', timezone: 'Asia/Shanghai', flag: '🇨🇳', region: 'East Asia' },
  { name: 'Dongguan', timezone: 'Asia/Shanghai', flag: '🇨🇳', region: 'East Asia' },
  { name: 'Foshan', timezone: 'Asia/Shanghai', flag: '🇨🇳', region: 'East Asia' },
  { name: 'Jinan', timezone: 'Asia/Shanghai', flag: '🇨🇳', region: 'East Asia' },
  { name: 'Dalian', timezone: 'Asia/Shanghai', flag: '🇨🇳', region: 'East Asia' },
  { name: 'Qingdao', timezone: 'Asia/Shanghai', flag: '🇨🇳', region: 'East Asia' },
  { name: 'Zhengzhou', timezone: 'Asia/Shanghai', flag: '🇨🇳', region: 'East Asia' },
  { name: 'Changsha', timezone: 'Asia/Shanghai', flag: '🇨🇳', region: 'East Asia' },
  { name: 'Kunming', timezone: 'Asia/Shanghai', flag: '🇨🇳', region: 'East Asia' },
  { name: 'Shenyang', timezone: 'Asia/Shanghai', flag: '🇨🇳', region: 'East Asia' },
  { name: 'Harbin', timezone: 'Asia/Shanghai', flag: '🇨🇳', region: 'East Asia' },
  { name: 'Changchun', timezone: 'Asia/Shanghai', flag: '🇨🇳', region: 'East Asia' },
  { name: 'Taiyuan', timezone: 'Asia/Shanghai', flag: '🇨🇳', region: 'East Asia' },
  { name: 'Shijiazhuang', timezone: 'Asia/Shanghai', flag: '🇨🇳', region: 'East Asia' },
  { name: 'Urumqi', timezone: 'Asia/Urumqi', flag: '🇨🇳', region: 'East Asia' },
  { name: 'Lhasa', timezone: 'Asia/Shanghai', flag: '🇨🇳', region: 'East Asia' },
  { name: 'Hong Kong', timezone: 'Asia/Hong_Kong', flag: '🇭🇰', region: 'East Asia' },
  { name: 'Macau', timezone: 'Asia/Macau', flag: '🇲🇴', region: 'East Asia' },
  { name: 'Taipei', timezone: 'Asia/Taipei', flag: '🇹🇼', region: 'East Asia' },
  { name: 'Kaohsiung', timezone: 'Asia/Taipei', flag: '🇹🇼', region: 'East Asia' },
  { name: 'Taichung', timezone: 'Asia/Taipei', flag: '🇹🇼', region: 'East Asia' },
  { name: 'Seoul', timezone: 'Asia/Seoul', flag: '🇰🇷', region: 'East Asia' },
  { name: 'Busan', timezone: 'Asia/Seoul', flag: '🇰🇷', region: 'East Asia' },
  { name: 'Incheon', timezone: 'Asia/Seoul', flag: '🇰🇷', region: 'East Asia' },
  { name: 'Daegu', timezone: 'Asia/Seoul', flag: '🇰🇷', region: 'East Asia' },
  { name: 'Daejeon', timezone: 'Asia/Seoul', flag: '🇰🇷', region: 'East Asia' },
  { name: 'Gwangju', timezone: 'Asia/Seoul', flag: '🇰🇷', region: 'East Asia' },
  { name: 'Ulsan', timezone: 'Asia/Seoul', flag: '🇰🇷', region: 'East Asia' },
  { name: 'Pyongyang', timezone: 'Asia/Pyongyang', flag: '🇰🇵', region: 'East Asia' },
  { name: 'Ulaanbaatar', timezone: 'Asia/Ulaanbaatar', flag: '🇲🇳', region: 'East Asia' },
  
  // Asia - Southeast Asia
  { name: 'Singapore', timezone: 'Asia/Singapore', flag: '🇸🇬', region: 'Southeast Asia' },
  { name: 'Bangkok', timezone: 'Asia/Bangkok', flag: '🇹🇭', region: 'Southeast Asia' },
  { name: 'Jakarta', timezone: 'Asia/Jakarta', flag: '🇮🇩', region: 'Southeast Asia' },
  { name: 'Manila', timezone: 'Asia/Manila', flag: '🇵🇭', region: 'Southeast Asia' },
  { name: 'Kuala Lumpur', timezone: 'Asia/Kuala_Lumpur', flag: '🇲🇾', region: 'Southeast Asia' },
  { name: 'Ho Chi Minh City', timezone: 'Asia/Ho_Chi_Minh', flag: '🇻🇳', region: 'Southeast Asia' },
  { name: 'Hanoi', timezone: 'Asia/Ho_Chi_Minh', flag: '🇻🇳', region: 'Southeast Asia' },
  { name: 'Yangon', timezone: 'Asia/Yangon', flag: '🇲🇲', region: 'Southeast Asia' },
  { name: 'Phnom Penh', timezone: 'Asia/Phnom_Penh', flag: '🇰🇭', region: 'Southeast Asia' },
  { name: 'Vientiane', timezone: 'Asia/Vientiane', flag: '🇱🇦', region: 'Southeast Asia' },
  { name: 'Bandar Seri Begawan', timezone: 'Asia/Brunei', flag: '🇧🇳', region: 'Southeast Asia' },
  { name: 'Surabaya', timezone: 'Asia/Jakarta', flag: '🇮🇩', region: 'Southeast Asia' },
  { name: 'Medan', timezone: 'Asia/Jakarta', flag: '🇮🇩', region: 'Southeast Asia' },
  { name: 'Bandung', timezone: 'Asia/Jakarta', flag: '🇮🇩', region: 'Southeast Asia' },
  { name: 'Semarang', timezone: 'Asia/Jakarta', flag: '🇮🇩', region: 'Southeast Asia' },
  { name: 'Makassar', timezone: 'Asia/Makassar', flag: '🇮🇩', region: 'Southeast Asia' },
  { name: 'Denpasar', timezone: 'Asia/Makassar', flag: '🇮🇩', region: 'Southeast Asia' },
  { name: 'Palembang', timezone: 'Asia/Jakarta', flag: '🇮🇩', region: 'Southeast Asia' },
  { name: 'Cebu City', timezone: 'Asia/Manila', flag: '🇵🇭', region: 'Southeast Asia' },
  { name: 'Davao City', timezone: 'Asia/Manila', flag: '🇵🇭', region: 'Southeast Asia' },
  { name: 'Quezon City', timezone: 'Asia/Manila', flag: '🇵🇭', region: 'Southeast Asia' },
  { name: 'Caloocan', timezone: 'Asia/Manila', flag: '🇵🇭', region: 'Southeast Asia' },
  { name: 'Penang', timezone: 'Asia/Kuala_Lumpur', flag: '🇲🇾', region: 'Southeast Asia' },
  { name: 'Johor Bahru', timezone: 'Asia/Kuala_Lumpur', flag: '🇲🇾', region: 'Southeast Asia' },
  { name: 'Ipoh', timezone: 'Asia/Kuala_Lumpur', flag: '🇲🇾', region: 'Southeast Asia' },
  { name: 'Chiang Mai', timezone: 'Asia/Bangkok', flag: '🇹🇭', region: 'Southeast Asia' },
  { name: 'Phuket', timezone: 'Asia/Bangkok', flag: '🇹🇭', region: 'Southeast Asia' },
  { name: 'Hatyai', timezone: 'Asia/Bangkok', flag: '🇹🇭', region: 'Southeast Asia' },
  { name: 'Da Nang', timezone: 'Asia/Ho_Chi_Minh', flag: '🇻🇳', region: 'Southeast Asia' },
  { name: 'Hai Phong', timezone: 'Asia/Ho_Chi_Minh', flag: '🇻🇳', region: 'Southeast Asia' },
  { name: 'Can Tho', timezone: 'Asia/Ho_Chi_Minh', flag: '🇻🇳', region: 'Southeast Asia' },
  { name: 'Mandalay', timezone: 'Asia/Yangon', flag: '🇲🇲', region: 'Southeast Asia' },
  { name: 'Naypyidaw', timezone: 'Asia/Yangon', flag: '🇲🇲', region: 'Southeast Asia' },
  
  // Asia - Central Asia
  { name: 'Almaty', timezone: 'Asia/Almaty', flag: '🇰🇿', region: 'Central Asia' },
  { name: 'Astana', timezone: 'Asia/Almaty', flag: '🇰🇿', region: 'Central Asia' },
  { name: 'Tashkent', timezone: 'Asia/Tashkent', flag: '🇺🇿', region: 'Central Asia' },
  { name: 'Samarkand', timezone: 'Asia/Samarkand', flag: '🇺🇿', region: 'Central Asia' },
  { name: 'Bishkek', timezone: 'Asia/Bishkek', flag: '🇰🇬', region: 'Central Asia' },
  { name: 'Dushanbe', timezone: 'Asia/Dushanbe', flag: '🇹🇯', region: 'Central Asia' },
  { name: 'Ashgabat', timezone: 'Asia/Ashgabat', flag: '🇹🇲', region: 'Central Asia' },
  
  // Africa
  { name: 'Cairo', timezone: 'Africa/Cairo', flag: '🇪🇬', region: 'Africa' },
  { name: 'Lagos', timezone: 'Africa/Lagos', flag: '🇳🇬', region: 'Africa' },
  { name: 'Kinshasa', timezone: 'Africa/Kinshasa', flag: '🇨🇩', region: 'Africa' },
  { name: 'Johannesburg', timezone: 'Africa/Johannesburg', flag: '🇿🇦', region: 'Africa' },
  { name: 'Cape Town', timezone: 'Africa/Johannesburg', flag: '🇿🇦', region: 'Africa' },
  { name: 'Nairobi', timezone: 'Africa/Nairobi', flag: '🇰🇪', region: 'Africa' },
  { name: 'Casablanca', timezone: 'Africa/Casablanca', flag: '🇲🇦', region: 'Africa' },
  { name: 'Algiers', timezone: 'Africa/Algiers', flag: '🇩🇿', region: 'Africa' },
  { name: 'Tunis', timezone: 'Africa/Tunis', flag: '🇹🇳', region: 'Africa' },
  { name: 'Tripoli', timezone: 'Africa/Tripoli', flag: '🇱🇾', region: 'Africa' },
  { name: 'Khartoum', timezone: 'Africa/Khartoum', flag: '🇸🇩', region: 'Africa' },
  { name: 'Addis Ababa', timezone: 'Africa/Addis_Ababa', flag: '🇪🇹', region: 'Africa' },
  { name: 'Dar es Salaam', timezone: 'Africa/Dar_es_Salaam', flag: '🇹🇿', region: 'Africa' },
  { name: 'Kampala', timezone: 'Africa/Kampala', flag: '🇺🇬', region: 'Africa' },
  { name: 'Accra', timezone: 'Africa/Accra', flag: '🇬🇭', region: 'Africa' },
  { name: 'Abidjan', timezone: 'Africa/Abidjan', flag: '🇨🇮', region: 'Africa' },
  { name: 'Dakar', timezone: 'Africa/Dakar', flag: '🇸🇳', region: 'Africa' },
  { name: 'Luanda', timezone: 'Africa/Luanda', flag: '🇦🇴', region: 'Africa' },
  { name: 'Maputo', timezone: 'Africa/Maputo', flag: '🇲🇿', region: 'Africa' },
  { name: 'Harare', timezone: 'Africa/Harare', flag: '🇿🇼', region: 'Africa' },
  { name: 'Lusaka', timezone: 'Africa/Lusaka', flag: '🇿🇲', region: 'Africa' },
  { name: 'Gaborone', timezone: 'Africa/Gaborone', flag: '🇧🇼', region: 'Africa' },
  { name: 'Windhoek', timezone: 'Africa/Windhoek', flag: '🇳🇦', region: 'Africa' },
  { name: 'Mbabane', timezone: 'Africa/Mbabane', flag: '🇸🇿', region: 'Africa' },
  { name: 'Maseru', timezone: 'Africa/Maseru', flag: '🇱🇸', region: 'Africa' },
  { name: 'Abuja', timezone: 'Africa/Lagos', flag: '🇳🇬', region: 'Africa' },
  { name: 'Ibadan', timezone: 'Africa/Lagos', flag: '🇳🇬', region: 'Africa' },
  { name: 'Kano', timezone: 'Africa/Lagos', flag: '🇳🇬', region: 'Africa' },
  { name: 'Port Harcourt', timezone: 'Africa/Lagos', flag: '🇳🇬', region: 'Africa' },
  { name: 'Benin City', timezone: 'Africa/Lagos', flag: '🇳🇬', region: 'Africa' },
  { name: 'Kaduna', timezone: 'Africa/Lagos', flag: '🇳🇬', region: 'Africa' },
  { name: 'Lubumbashi', timezone: 'Africa/Lubumbashi', flag: '🇨🇩', region: 'Africa' },
  { name: 'Mbuji-Mayi', timezone: 'Africa/Lubumbashi', flag: '🇨🇩', region: 'Africa' },
  { name: 'Kisangani', timezone: 'Africa/Lubumbashi', flag: '🇨🇩', region: 'Africa' },
  { name: 'Durban', timezone: 'Africa/Johannesburg', flag: '🇿🇦', region: 'Africa' },
  { name: 'Pretoria', timezone: 'Africa/Johannesburg', flag: '🇿🇦', region: 'Africa' },
  { name: 'Port Elizabeth', timezone: 'Africa/Johannesburg', flag: '🇿🇦', region: 'Africa' },
  { name: 'Mombasa', timezone: 'Africa/Nairobi', flag: '🇰🇪', region: 'Africa' },
  { name: 'Kisumu', timezone: 'Africa/Nairobi', flag: '🇰🇪', region: 'Africa' },
  { name: 'Rabat', timezone: 'Africa/Casablanca', flag: '🇲🇦', region: 'Africa' },
  { name: 'Marrakech', timezone: 'Africa/Casablanca', flag: '🇲🇦', region: 'Africa' },
  { name: 'Fes', timezone: 'Africa/Casablanca', flag: '🇲🇦', region: 'Africa' },
  { name: 'Oran', timezone: 'Africa/Algiers', flag: '🇩🇿', region: 'Africa' },
  { name: 'Constantine', timezone: 'Africa/Algiers', flag: '🇩🇿', region: 'Africa' },
  { name: 'Sfax', timezone: 'Africa/Tunis', flag: '🇹🇳', region: 'Africa' },
  { name: 'Sousse', timezone: 'Africa/Tunis', flag: '🇹🇳', region: 'Africa' },
  { name: 'Benghazi', timezone: 'Africa/Tripoli', flag: '🇱🇾', region: 'Africa' },
  { name: 'Port Sudan', timezone: 'Africa/Khartoum', flag: '🇸🇩', region: 'Africa' },
  { name: 'Dire Dawa', timezone: 'Africa/Addis_Ababa', flag: '🇪🇹', region: 'Africa' },
  { name: 'Mekele', timezone: 'Africa/Addis_Ababa', flag: '🇪🇹', region: 'Africa' },
  { name: 'Zanzibar', timezone: 'Africa/Dar_es_Salaam', flag: '🇹🇿', region: 'Africa' },
  { name: 'Mwanza', timezone: 'Africa/Dar_es_Salaam', flag: '🇹🇿', region: 'Africa' },
  { name: 'Entebbe', timezone: 'Africa/Kampala', flag: '🇺🇬', region: 'Africa' },
  { name: 'Kumasi', timezone: 'Africa/Accra', flag: '🇬🇭', region: 'Africa' },
  { name: 'Tamale', timezone: 'Africa/Accra', flag: '🇬🇭', region: 'Africa' },
  { name: 'Bouake', timezone: 'Africa/Abidjan', flag: '🇨🇮', region: 'Africa' },
  { name: 'Yamoussoukro', timezone: 'Africa/Abidjan', flag: '🇨🇮', region: 'Africa' },
  { name: 'Thies', timezone: 'Africa/Dakar', flag: '🇸🇳', region: 'Africa' },
  { name: 'Huambo', timezone: 'Africa/Luanda', flag: '🇦🇴', region: 'Africa' },
  { name: 'Lobito', timezone: 'Africa/Luanda', flag: '🇦🇴', region: 'Africa' },
  { name: 'Beira', timezone: 'Africa/Maputo', flag: '🇲🇿', region: 'Africa' },
  { name: 'Nampula', timezone: 'Africa/Maputo', flag: '🇲🇿', region: 'Africa' },
  { name: 'Bulawayo', timezone: 'Africa/Harare', flag: '🇿🇼', region: 'Africa' },
  { name: 'Chitungwiza', timezone: 'Africa/Harare', flag: '🇿🇼', region: 'Africa' },
  { name: 'Ndola', timezone: 'Africa/Lusaka', flag: '🇿🇲', region: 'Africa' },
  { name: 'Kitwe', timezone: 'Africa/Lusaka', flag: '🇿🇲', region: 'Africa' },
  { name: 'Francistown', timezone: 'Africa/Gaborone', flag: '🇧🇼', region: 'Africa' },
  { name: 'Oshakati', timezone: 'Africa/Windhoek', flag: '🇳🇦', region: 'Africa' },
  
  // Oceania
  { name: 'Sydney', timezone: 'Australia/Sydney', flag: '🇦🇺', region: 'Oceania' },
  { name: 'Melbourne', timezone: 'Australia/Melbourne', flag: '🇦🇺', region: 'Oceania' },
  { name: 'Brisbane', timezone: 'Australia/Brisbane', flag: '🇦🇺', region: 'Oceania' },
  { name: 'Perth', timezone: 'Australia/Perth', flag: '🇦🇺', region: 'Oceania' },
  { name: 'Adelaide', timezone: 'Australia/Adelaide', flag: '🇦🇺', region: 'Oceania' },
  { name: 'Darwin', timezone: 'Australia/Darwin', flag: '🇦🇺', region: 'Oceania' },
  { name: 'Hobart', timezone: 'Australia/Hobart', flag: '🇦🇺', region: 'Oceania' },
  { name: 'Canberra', timezone: 'Australia/Sydney', flag: '🇦🇺', region: 'Oceania' },
  { name: 'Gold Coast', timezone: 'Australia/Brisbane', flag: '🇦🇺', region: 'Oceania' },
  { name: 'Newcastle', timezone: 'Australia/Sydney', flag: '🇦🇺', region: 'Oceania' },
  { name: 'Wollongong', timezone: 'Australia/Sydney', flag: '🇦🇺', region: 'Oceania' },
  { name: 'Geelong', timezone: 'Australia/Melbourne', flag: '🇦🇺', region: 'Oceania' },
  { name: 'Townsville', timezone: 'Australia/Brisbane', flag: '🇦🇺', region: 'Oceania' },
  { name: 'Cairns', timezone: 'Australia/Brisbane', flag: '🇦🇺', region: 'Oceania' },
  { name: 'Toowoomba', timezone: 'Australia/Brisbane', flag: '🇦🇺', region: 'Oceania' },
  { name: 'Ballarat', timezone: 'Australia/Melbourne', flag: '🇦🇺', region: 'Oceania' },
  { name: 'Bendigo', timezone: 'Australia/Melbourne', flag: '🇦🇺', region: 'Oceania' },
  { name: 'Albury', timezone: 'Australia/Sydney', flag: '🇦🇺', region: 'Oceania' },
  { name: 'Launceston', timezone: 'Australia/Hobart', flag: '🇦🇺', region: 'Oceania' },
  { name: 'Mackay', timezone: 'Australia/Brisbane', flag: '🇦🇺', region: 'Oceania' },
  { name: 'Rockhampton', timezone: 'Australia/Brisbane', flag: '🇦🇺', region: 'Oceania' },
  { name: 'Bunbury', timezone: 'Australia/Perth', flag: '🇦🇺', region: 'Oceania' },
  { name: 'Coffs Harbour', timezone: 'Australia/Sydney', flag: '🇦🇺', region: 'Oceania' },
  { name: 'Wagga Wagga', timezone: 'Australia/Sydney', flag: '🇦🇺', region: 'Oceania' },
  { name: 'Hervey Bay', timezone: 'Australia/Brisbane', flag: '🇦🇺', region: 'Oceania' },
  { name: 'Port Macquarie', timezone: 'Australia/Sydney', flag: '🇦🇺', region: 'Oceania' },
  { name: 'Auckland', timezone: 'Pacific/Auckland', flag: '🇳🇿', region: 'Oceania' },
  { name: 'Wellington', timezone: 'Pacific/Auckland', flag: '🇳🇿', region: 'Oceania' },
  { name: 'Christchurch', timezone: 'Pacific/Auckland', flag: '🇳🇿', region: 'Oceania' },
  { name: 'Hamilton', timezone: 'Pacific/Auckland', flag: '🇳🇿', region: 'Oceania' },
  { name: 'Tauranga', timezone: 'Pacific/Auckland', flag: '🇳🇿', region: 'Oceania' },
  { name: 'Napier', timezone: 'Pacific/Auckland', flag: '🇳🇿', region: 'Oceania' },
  { name: 'Palmerston North', timezone: 'Pacific/Auckland', flag: '🇳🇿', region: 'Oceania' },
  { name: 'Dunedin', timezone: 'Pacific/Auckland', flag: '🇳🇿', region: 'Oceania' },
  { name: 'Invercargill', timezone: 'Pacific/Auckland', flag: '🇳🇿', region: 'Oceania' },
  { name: 'Suva', timezone: 'Pacific/Fiji', flag: '🇫🇯', region: 'Oceania' },
  { name: 'Nadi', timezone: 'Pacific/Fiji', flag: '🇫🇯', region: 'Oceania' },
  { name: 'Port Moresby', timezone: 'Pacific/Port_Moresby', flag: '🇵🇬', region: 'Oceania' },
  { name: 'Lae', timezone: 'Pacific/Port_Moresby', flag: '🇵🇬', region: 'Oceania' },
  { name: 'Noumea', timezone: 'Pacific/Noumea', flag: '🇳🇨', region: 'Oceania' },
  { name: 'Port Vila', timezone: 'Pacific/Efate', flag: '🇻🇺', region: 'Oceania' },
  { name: 'Honiara', timezone: 'Pacific/Guadalcanal', flag: '🇸🇧', region: 'Oceania' },
  { name: 'Nuku\'alofa', timezone: 'Pacific/Tongatapu', flag: '🇹🇴', region: 'Oceania' },
  { name: 'Apia', timezone: 'Pacific/Apia', flag: '🇼🇸', region: 'Oceania' },
  { name: 'Pago Pago', timezone: 'Pacific/Pago_Pago', flag: '🇦🇸', region: 'Oceania' },
  { name: 'Honolulu', timezone: 'Pacific/Honolulu', flag: '🇺🇸', region: 'Oceania' },
  { name: 'Anchorage', timezone: 'America/Anchorage', flag: '🇺🇸', region: 'Oceania' },
  
  // Pacific Islands
  { name: 'Guam', timezone: 'Pacific/Guam', flag: '🇬🇺', region: 'Pacific' },
  { name: 'Saipan', timezone: 'Pacific/Saipan', flag: '🇲🇵', region: 'Pacific' },
  { name: 'Palikir', timezone: 'Pacific/Pohnpei', flag: '🇫🇲', region: 'Pacific' },
  { name: 'Majuro', timezone: 'Pacific/Majuro', flag: '🇲🇭', region: 'Pacific' },
  { name: 'Tarawa', timezone: 'Pacific/Tarawa', flag: '🇰🇮', region: 'Pacific' },
  { name: 'Funafuti', timezone: 'Pacific/Funafuti', flag: '🇹🇻', region: 'Pacific' },
  { name: 'Papeete', timezone: 'Pacific/Tahiti', flag: '🇵🇫', region: 'Pacific' },
  { name: 'Rarotonga', timezone: 'Pacific/Rarotonga', flag: '🇨🇰', region: 'Pacific' },
  { name: 'Avarua', timezone: 'Pacific/Rarotonga', flag: '🇨🇰', region: 'Pacific' },
  
  // Atlantic Islands
  { name: 'Reykjavik', timezone: 'Atlantic/Reykjavik', flag: '🇮🇸', region: 'Atlantic' },
  { name: 'Torshavn', timezone: 'Atlantic/Faroe', flag: '🇫🇴', region: 'Atlantic' },
  { name: 'Azores', timezone: 'Atlantic/Azores', flag: '🇵🇹', region: 'Atlantic' },
  { name: 'Madeira', timezone: 'Atlantic/Madeira', flag: '🇵🇹', region: 'Atlantic' },
  { name: 'Canary Islands', timezone: 'Atlantic/Canary', flag: '🇪🇸', region: 'Atlantic' },
  { name: 'Cape Verde', timezone: 'Atlantic/Cape_Verde', flag: '🇨🇻', region: 'Atlantic' },
  { name: 'Bermuda', timezone: 'Atlantic/Bermuda', flag: '🇧🇲', region: 'Atlantic' },
  { name: 'South Georgia', timezone: 'Atlantic/South_Georgia', flag: '🇬🇸', region: 'Atlantic' },
  
  // Indian Ocean
  { name: 'Mauritius', timezone: 'Indian/Mauritius', flag: '🇲🇺', region: 'Indian Ocean' },
  { name: 'Seychelles', timezone: 'Indian/Mahe', flag: '🇸🇨', region: 'Indian Ocean' },
  { name: 'Reunion', timezone: 'Indian/Reunion', flag: '🇷🇪', region: 'Indian Ocean' },
  { name: 'Comoros', timezone: 'Indian/Comoro', flag: '🇰🇲', region: 'Indian Ocean' },
  { name: 'Antananarivo', timezone: 'Indian/Antananarivo', flag: '🇲🇬', region: 'Indian Ocean' },
  { name: 'Port Louis', timezone: 'Indian/Mauritius', flag: '🇲🇺', region: 'Indian Ocean' },
  { name: 'Victoria', timezone: 'Indian/Mahe', flag: '🇸🇨', region: 'Indian Ocean' },
  { name: 'Saint-Denis', timezone: 'Indian/Reunion', flag: '🇷🇪', region: 'Indian Ocean' },
  { name: 'Moroni', timezone: 'Indian/Comoro', flag: '🇰🇲', region: 'Indian Ocean' },
  
  // Additional Major Cities
  { name: 'Monaco', timezone: 'Europe/Monaco', flag: '🇲🇨', region: 'Europe' },
  { name: 'Vatican City', timezone: 'Europe/Vatican', flag: '🇻🇦', region: 'Europe' },
  { name: 'San Marino', timezone: 'Europe/San_Marino', flag: '🇸🇲', region: 'Europe' },
  { name: 'Liechtenstein', timezone: 'Europe/Vaduz', flag: '🇱🇮', region: 'Europe' },
  { name: 'Gibraltar', timezone: 'Europe/Gibraltar', flag: '🇬🇮', region: 'Europe' },
  { name: 'Malta', timezone: 'Europe/Malta', flag: '🇲🇹', region: 'Europe' },
  { name: 'Iceland', timezone: 'Atlantic/Reykjavik', flag: '🇮🇸', region: 'Europe' },
];

// Export for use in popup.js
if (typeof module !== 'undefined' && module.exports) {
  module.exports = allTimezones;
}




